//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFG.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class conn
    {
        public int conn_id { get; set; }
        public Nullable<int> conn_drill_id { get; set; }
        public Nullable<int> conn_brick_id { get; set; }
    
        public virtual brick brick { get; set; }
        public virtual drill drill { get; set; }
    }
}
